// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CustomerReplyCreate
 *
 * Customer 公开回复工单的严格输入。by AI.Coding
 */
export type CustomerReplyCreate = {
    /**
     * Content
     */
    content: string;
};

/**
 * DeleteTicketRequest
 *
 * Admin 删除工单时必须显式确认的输入。by AI.Coding
 */
export type DeleteTicketRequest = {
    /**
     * Confirm
     */
    confirm: true;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 *
 * 通用消息响应。by AI.Coding
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 *
 * 密码重置请求。by AI.Coding
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * TicketAssign
 *
 * Admin 分派或转派工单的严格输入。by AI.Coding
 */
export type TicketAssign = {
    /**
     * Assignee Id
     */
    assignee_id: string;
};

/**
 * TicketAttributesUpdate
 *
 * 修改工单优先级或分类的严格输入。by AI.Coding
 */
export type TicketAttributesUpdate = {
    priority?: TicketPriority | null;
    category?: TicketCategory | null;
};

/**
 * TicketAuditAction
 *
 * 工单审计动作枚举。by AI.Coding
 */
export type TicketAuditAction = 'TAKEN' | 'ASSIGNED' | 'REASSIGNED' | 'UNASSIGNED' | 'STATUS_CHANGED' | 'PRIORITY_CHANGED' | 'CATEGORY_CHANGED' | 'DELETED';

/**
 * TicketAuditPublic
 *
 * 按角色裁剪后的结构化工单审计响应。by AI.Coding
 */
export type TicketAuditPublic = {
    /**
     * Id
     */
    id: string;
    action: TicketAuditAction;
    actor: UserSummary;
    /**
     * Old Value
     */
    old_value?: {
        [key: string]: unknown;
    } | null;
    /**
     * New Value
     */
    new_value?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TicketCategory
 *
 * 工单分类枚举。by AI.Coding
 */
export type TicketCategory = 'ACCOUNT' | 'BILLING' | 'PRODUCT' | 'BUG' | 'FEATURE_REQUEST' | 'OTHER';

/**
 * TicketCreate
 *
 * Customer 创建工单的严格输入。by AI.Coding
 */
export type TicketCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    category: TicketCategory;
};

/**
 * TicketDetailPublic
 *
 * 包含角色安全时间线的工单详情响应。by AI.Coding
 */
export type TicketDetailPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Ticket Number
     */
    ticket_number: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    status: TicketStatus;
    priority: TicketPriority;
    category: TicketCategory;
    requester: UserSummary;
    assignee?: UserSummary | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Messages
     */
    messages: Array<TicketMessagePublic>;
    /**
     * Audit Logs
     */
    audit_logs: Array<TicketAuditPublic>;
};

/**
 * TicketMessageCreate
 *
 * Staff 创建公开回复或内部备注的严格输入。by AI.Coding
 */
export type TicketMessageCreate = {
    message_type: TicketMessageType;
    /**
     * Content
     */
    content: string;
};

/**
 * TicketMessagePublic
 *
 * 按角色裁剪后的工单消息响应。by AI.Coding
 */
export type TicketMessagePublic = {
    /**
     * Id
     */
    id: string;
    author: UserSummary;
    message_type: TicketMessageType;
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TicketMessageType
 *
 * 工单消息类型枚举。by AI.Coding
 */
export type TicketMessageType = 'PUBLIC_REPLY' | 'INTERNAL_NOTE';

/**
 * TicketPriority
 *
 * 工单优先级枚举。by AI.Coding
 */
export type TicketPriority = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';

/**
 * TicketPublic
 *
 * 不包含消息和审计时间线的工单公开响应。by AI.Coding
 */
export type TicketPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Ticket Number
     */
    ticket_number: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    status: TicketStatus;
    priority: TicketPriority;
    category: TicketCategory;
    requester: UserSummary;
    assignee?: UserSummary | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * TicketStatisticsPublic
 *
 * 按角色返回工单统计计数。by AI.Coding
 */
export type TicketStatisticsPublic = {
    role: UserRole;
    /**
     * Status Counts
     */
    status_counts?: {
        [key in TicketStatus]?: number;
    };
    /**
     * Priority Counts
     */
    priority_counts?: {
        [key in TicketPriority]?: number;
    };
    /**
     * Unassigned Count
     */
    unassigned_count?: number;
    /**
     * Assigned To Me Count
     */
    assigned_to_me_count?: number;
    /**
     * Waiting For Customer Count
     */
    waiting_for_customer_count?: number;
};

/**
 * TicketStatus
 *
 * 工单状态枚举。by AI.Coding
 */
export type TicketStatus = 'OPEN' | 'IN_PROGRESS' | 'WAITING_FOR_CUSTOMER' | 'RESOLVED' | 'CLOSED';

/**
 * TicketStatusUpdate
 *
 * 主动修改工单状态的严格输入。by AI.Coding
 */
export type TicketStatusUpdate = {
    status: TicketStatus;
};

/**
 * TicketsPublic
 *
 * 工单服务端分页响应。by AI.Coding
 */
export type TicketsPublic = {
    /**
     * Data
     */
    data: Array<TicketPublic>;
    /**
     * Count
     */
    count: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * Token
 *
 * 访问令牌响应。by AI.Coding
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 *
 * 当前用户修改密码请求。by AI.Coding
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 *
 * 管理员创建用户请求，保持当前模板字段兼容。by AI.Coding
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 *
 * 用户公开响应，不包含密码字段。by AI.Coding
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    role?: UserRole;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 *
 * 公开注册请求，不接受角色和启用状态字段。by AI.Coding
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserRole
 *
 * 用户单角色枚举。by AI.Coding
 */
export type UserRole = 'CUSTOMER' | 'AGENT' | 'ADMIN';

/**
 * UserSummary
 *
 * 嵌入工单响应的最小用户公开摘要。by AI.Coding
 */
export type UserSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    role: UserRole;
};

/**
 * UserUpdate
 *
 * 管理员更新用户请求，保持现有接口名称和字段。by AI.Coding
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 *
 * 当前用户更新个人资料请求。by AI.Coding
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 *
 * 用户分页响应。by AI.Coding
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type ticketsReadTicketStatisticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tickets/statistics';
};

export type ticketsReadTicketStatisticsResponses = {
    /**
     * Successful Response
     */
    200: TicketStatisticsPublic;
};

export type ticketsReadTicketStatisticsResponse = ticketsReadTicketStatisticsResponses[keyof ticketsReadTicketStatisticsResponses];

export type ticketsListTicketsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: TicketStatus | null;
        /**
         * Priority
         */
        priority?: TicketPriority | null;
        /**
         * Category
         */
        category?: TicketCategory | null;
        /**
         * Assignee Id
         */
        assignee_id?: string | null;
        /**
         * Query
         */
        query?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/tickets';
};

export type ticketsListTicketsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ticketsListTicketsError = ticketsListTicketsErrors[keyof ticketsListTicketsErrors];

export type ticketsListTicketsResponses = {
    /**
     * Successful Response
     */
    200: TicketsPublic;
};

export type ticketsListTicketsResponse = ticketsListTicketsResponses[keyof ticketsListTicketsResponses];

export type ticketsCreateTicketData = {
    body: TicketCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tickets';
};

export type ticketsCreateTicketErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ticketsCreateTicketError = ticketsCreateTicketErrors[keyof ticketsCreateTicketErrors];

export type ticketsCreateTicketResponses = {
    /**
     * Successful Response
     */
    201: TicketDetailPublic;
};

export type ticketsCreateTicketResponse = ticketsCreateTicketResponses[keyof ticketsCreateTicketResponses];

export type ticketsDeleteTicketData = {
    body: DeleteTicketRequest;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}';
};

export type ticketsDeleteTicketErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ticketsDeleteTicketError = ticketsDeleteTicketErrors[keyof ticketsDeleteTicketErrors];

export type ticketsDeleteTicketResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ticketsDeleteTicketResponse = ticketsDeleteTicketResponses[keyof ticketsDeleteTicketResponses];

export type ticketsReadTicketData = {
    body?: never;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}';
};

export type ticketsReadTicketErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ticketsReadTicketError = ticketsReadTicketErrors[keyof ticketsReadTicketErrors];

export type ticketsReadTicketResponses = {
    /**
     * Successful Response
     */
    200: TicketDetailPublic;
};

export type ticketsReadTicketResponse = ticketsReadTicketResponses[keyof ticketsReadTicketResponses];

export type ticketsClaimTicketData = {
    body?: never;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}/claim';
};

export type ticketsClaimTicketErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ticketsClaimTicketError = ticketsClaimTicketErrors[keyof ticketsClaimTicketErrors];

export type ticketsClaimTicketResponses = {
    /**
     * Successful Response
     */
    200: TicketDetailPublic;
};

export type ticketsClaimTicketResponse = ticketsClaimTicketResponses[keyof ticketsClaimTicketResponses];

export type ticketsUnassignTicketData = {
    body?: never;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}/assignee';
};

export type ticketsUnassignTicketErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ticketsUnassignTicketError = ticketsUnassignTicketErrors[keyof ticketsUnassignTicketErrors];

export type ticketsUnassignTicketResponses = {
    /**
     * Successful Response
     */
    200: TicketDetailPublic;
};

export type ticketsUnassignTicketResponse = ticketsUnassignTicketResponses[keyof ticketsUnassignTicketResponses];

export type ticketsAssignTicketData = {
    body: TicketAssign;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}/assignee';
};

export type ticketsAssignTicketErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ticketsAssignTicketError = ticketsAssignTicketErrors[keyof ticketsAssignTicketErrors];

export type ticketsAssignTicketResponses = {
    /**
     * Successful Response
     */
    200: TicketDetailPublic;
};

export type ticketsAssignTicketResponse = ticketsAssignTicketResponses[keyof ticketsAssignTicketResponses];

export type ticketsAddCustomerReplyData = {
    body: CustomerReplyCreate;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}/replies';
};

export type ticketsAddCustomerReplyErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ticketsAddCustomerReplyError = ticketsAddCustomerReplyErrors[keyof ticketsAddCustomerReplyErrors];

export type ticketsAddCustomerReplyResponses = {
    /**
     * Successful Response
     */
    201: TicketMessagePublic;
};

export type ticketsAddCustomerReplyResponse = ticketsAddCustomerReplyResponses[keyof ticketsAddCustomerReplyResponses];

export type ticketsAddStaffMessageData = {
    body: TicketMessageCreate;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}/messages';
};

export type ticketsAddStaffMessageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ticketsAddStaffMessageError = ticketsAddStaffMessageErrors[keyof ticketsAddStaffMessageErrors];

export type ticketsAddStaffMessageResponses = {
    /**
     * Successful Response
     */
    201: TicketMessagePublic;
};

export type ticketsAddStaffMessageResponse = ticketsAddStaffMessageResponses[keyof ticketsAddStaffMessageResponses];

export type ticketsUpdateStatusData = {
    body: TicketStatusUpdate;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}/status';
};

export type ticketsUpdateStatusErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ticketsUpdateStatusError = ticketsUpdateStatusErrors[keyof ticketsUpdateStatusErrors];

export type ticketsUpdateStatusResponses = {
    /**
     * Successful Response
     */
    200: TicketDetailPublic;
};

export type ticketsUpdateStatusResponse = ticketsUpdateStatusResponses[keyof ticketsUpdateStatusResponses];

export type ticketsUpdateAttributesData = {
    body: TicketAttributesUpdate;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}/attributes';
};

export type ticketsUpdateAttributesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ticketsUpdateAttributesError = ticketsUpdateAttributesErrors[keyof ticketsUpdateAttributesErrors];

export type ticketsUpdateAttributesResponses = {
    /**
     * Successful Response
     */
    200: TicketDetailPublic;
};

export type ticketsUpdateAttributesResponse = ticketsUpdateAttributesResponses[keyof ticketsUpdateAttributesResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
