"""API Schema 的稳定聚合导出入口。by AI.Coding"""

from app.schemas.ai import (
    AgentEventPublic,
    ConversationCreate,
    ConversationPublic,
    MessageCreate,
    ProviderConfigPatch,
    ProviderConfigPublic,
    ProviderTestKind,
    ProviderTestRequest,
    ProviderTestResult,
)
from app.schemas.attachment import AttachmentPublic
from app.schemas.auth import NewPassword, Token, TokenPayload, UpdatePassword
from app.schemas.common import ErrorResponse, Message
from app.schemas.knowledge import (
    DocumentIngestionJobPublic,
    KnowledgeDocumentPublic,
    KnowledgeSearchRequest,
    RetrievedChunkPublic,
)
from app.schemas.ticket import (
    DeleteTicketRequest,
    TicketAssign,
    TicketAuditPublic,
    TicketCreate,
    TicketDetailPublic,
    TicketFilters,
    TicketMessagePublic,
    TicketPublic,
    TicketsPublic,
    TicketStatisticsPublic,
    UserSummary,
)
from app.schemas.tools import ToolPermissionPatch, ToolPermissionPublic
from app.schemas.user import (
    UserCreate,
    UserCreateAdmin,
    UserFilters,
    UserPublic,
    UserRegister,
    UsersPublic,
    UserUpdate,
    UserUpdateAdmin,
    UserUpdateMe,
)

__all__ = [
    "ErrorResponse",
    "Message",
    "NewPassword",
    "ProviderConfigPatch",
    "AgentEventPublic",
    "AttachmentPublic",
    "ConversationCreate",
    "ConversationPublic",
    "MessageCreate",
    "ProviderConfigPublic",
    "ProviderTestKind",
    "ProviderTestRequest",
    "ProviderTestResult",
    "DocumentIngestionJobPublic",
    "KnowledgeDocumentPublic",
    "KnowledgeSearchRequest",
    "RetrievedChunkPublic",
    "DeleteTicketRequest",
    "TicketAssign",
    "TicketAuditPublic",
    "TicketCreate",
    "TicketDetailPublic",
    "TicketFilters",
    "TicketMessagePublic",
    "ToolPermissionPatch",
    "ToolPermissionPublic",
    "TicketPublic",
    "TicketStatisticsPublic",
    "TicketsPublic",
    "Token",
    "TokenPayload",
    "UpdatePassword",
    "UserCreate",
    "UserCreateAdmin",
    "UserFilters",
    "UserPublic",
    "UserRegister",
    "UsersPublic",
    "UserSummary",
    "UserUpdate",
    "UserUpdateAdmin",
    "UserUpdateMe",
]
