/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutQueueRouteImport } from './routes/_layout/queue'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutTicketsRouteImport } from './routes/_layout/tickets'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as LayoutAdminTicketsRouteImport } from './routes/_layout/admin/tickets'
import { Route as LayoutQueueTicketIdRouteImport } from './routes/_layout/queue/$ticketId'
import { Route as LayoutTicketsTicketIdRouteImport } from './routes/_layout/tickets/$ticketId'
import { Route as LayoutAdminTicketsIndexRouteImport } from './routes/_layout/admin/tickets/index'
import { Route as LayoutAdminTicketsTicketIdRouteImport } from './routes/_layout/admin/tickets/$ticketId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQueueRoute = LayoutQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTicketsRoute = LayoutTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminTicketsRoute = LayoutAdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutQueueTicketIdRoute = LayoutQueueTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => LayoutQueueRoute,
} as any)
const LayoutTicketsTicketIdRoute = LayoutTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => LayoutTicketsRoute,
} as any)
const LayoutAdminTicketsIndexRoute = LayoutAdminTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminTicketsRoute,
} as any)
const LayoutAdminTicketsTicketIdRoute =
  LayoutAdminTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => LayoutAdminTicketsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/queue': typeof LayoutQueueRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/tickets': typeof LayoutTicketsRouteWithChildren
  '/admin/tickets': typeof LayoutAdminTicketsRouteWithChildren
  '/queue/$ticketId': typeof LayoutQueueTicketIdRoute
  '/tickets/$ticketId': typeof LayoutTicketsTicketIdRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/admin/tickets/$ticketId': typeof LayoutAdminTicketsTicketIdRoute
  '/admin/tickets/': typeof LayoutAdminTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/queue': typeof LayoutQueueRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/tickets': typeof LayoutTicketsRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/queue/$ticketId': typeof LayoutQueueTicketIdRoute
  '/tickets/$ticketId': typeof LayoutTicketsTicketIdRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/admin/tickets/$ticketId': typeof LayoutAdminTicketsTicketIdRoute
  '/admin/tickets': typeof LayoutAdminTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/queue': typeof LayoutQueueRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tickets': typeof LayoutTicketsRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/tickets': typeof LayoutAdminTicketsRouteWithChildren
  '/_layout/queue/$ticketId': typeof LayoutQueueTicketIdRoute
  '/_layout/tickets/$ticketId': typeof LayoutTicketsTicketIdRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/admin/tickets/$ticketId': typeof LayoutAdminTicketsTicketIdRoute
  '/_layout/admin/tickets/': typeof LayoutAdminTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/queue'
    | '/settings'
    | '/tickets'
    | '/admin/tickets'
    | '/queue/$ticketId'
    | '/tickets/$ticketId'
    | '/admin/'
    | '/admin/tickets/$ticketId'
    | '/admin/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/queue'
    | '/settings'
    | '/tickets'
    | '/'
    | '/queue/$ticketId'
    | '/tickets/$ticketId'
    | '/admin'
    | '/admin/tickets/$ticketId'
    | '/admin/tickets'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/queue'
    | '/_layout/settings'
    | '/_layout/tickets'
    | '/_layout/'
    | '/_layout/admin/tickets'
    | '/_layout/queue/$ticketId'
    | '/_layout/tickets/$ticketId'
    | '/_layout/admin/'
    | '/_layout/admin/tickets/$ticketId'
    | '/_layout/admin/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/queue': {
      id: '/_layout/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof LayoutQueueRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tickets': {
      id: '/_layout/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof LayoutTicketsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/tickets': {
      id: '/_layout/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof LayoutAdminTicketsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/queue/$ticketId': {
      id: '/_layout/queue/$ticketId'
      path: '/$ticketId'
      fullPath: '/queue/$ticketId'
      preLoaderRoute: typeof LayoutQueueTicketIdRouteImport
      parentRoute: typeof LayoutQueueRoute
    }
    '/_layout/tickets/$ticketId': {
      id: '/_layout/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof LayoutTicketsTicketIdRouteImport
      parentRoute: typeof LayoutTicketsRoute
    }
    '/_layout/admin/tickets/': {
      id: '/_layout/admin/tickets/'
      path: '/'
      fullPath: '/admin/tickets/'
      preLoaderRoute: typeof LayoutAdminTicketsIndexRouteImport
      parentRoute: typeof LayoutAdminTicketsRoute
    }
    '/_layout/admin/tickets/$ticketId': {
      id: '/_layout/admin/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/admin/tickets/$ticketId'
      preLoaderRoute: typeof LayoutAdminTicketsTicketIdRouteImport
      parentRoute: typeof LayoutAdminTicketsRoute
    }
  }
}

interface LayoutAdminTicketsRouteChildren {
  LayoutAdminTicketsTicketIdRoute: typeof LayoutAdminTicketsTicketIdRoute
  LayoutAdminTicketsIndexRoute: typeof LayoutAdminTicketsIndexRoute
}

const LayoutAdminTicketsRouteChildren: LayoutAdminTicketsRouteChildren = {
  LayoutAdminTicketsTicketIdRoute: LayoutAdminTicketsTicketIdRoute,
  LayoutAdminTicketsIndexRoute: LayoutAdminTicketsIndexRoute,
}

const LayoutAdminTicketsRouteWithChildren =
  LayoutAdminTicketsRoute._addFileChildren(LayoutAdminTicketsRouteChildren)

interface LayoutAdminRouteChildren {
  LayoutAdminTicketsRoute: typeof LayoutAdminTicketsRouteWithChildren
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminTicketsRoute: LayoutAdminTicketsRouteWithChildren,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutQueueRouteChildren {
  LayoutQueueTicketIdRoute: typeof LayoutQueueTicketIdRoute
}

const LayoutQueueRouteChildren: LayoutQueueRouteChildren = {
  LayoutQueueTicketIdRoute: LayoutQueueTicketIdRoute,
}

const LayoutQueueRouteWithChildren = LayoutQueueRoute._addFileChildren(
  LayoutQueueRouteChildren,
)

interface LayoutTicketsRouteChildren {
  LayoutTicketsTicketIdRoute: typeof LayoutTicketsTicketIdRoute
}

const LayoutTicketsRouteChildren: LayoutTicketsRouteChildren = {
  LayoutTicketsTicketIdRoute: LayoutTicketsTicketIdRoute,
}

const LayoutTicketsRouteWithChildren = LayoutTicketsRoute._addFileChildren(
  LayoutTicketsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutQueueRoute: typeof LayoutQueueRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTicketsRoute: typeof LayoutTicketsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutQueueRoute: LayoutQueueRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTicketsRoute: LayoutTicketsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
